# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('char_names', models.CharField(default='', max_length=50)),
                ('time_added', models.DateTimeField()),
                ('path', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=20)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l.ImageDetails')),
            ],
        ),
    ]
