# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='image_id',
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='char_names',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
        migrations.AddField(
            model_name='imagetags',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l.ImageDetails'),
        ),
    ]
