# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l', '0003_auto_20170721_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetails',
            name='time_added',
            field=models.DateTimeField(),
        ),
    ]
