# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l', '0004_auto_20170721_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTags',
            new_name='ImageTag',
        ),
    ]
